# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3edc964fe260ad89309b952e18184dc37e63e93f6e7aaef471b7651f03311e50ded023cf6ea50e3f02aa09a95610eae99088c46071aaa1c169629214ea7f35fa

test:
  secret_key_base: 20594d4b68afc2a9034a985f83183b0b49c3fdf89a6453e9128daca16ce21f4b1a058ce42f0b7afe375f1a31d3337491b774c596701b15b52de19b7df3ab6f31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
